source 'git@github.com:uspython/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

workspace '../JZSwiftWarpper.xcworkspace'

target 'Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
  pod 'JZSwiftWarpper', :path => '../'
#  target 'ExampleTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#  target 'ExampleUITests' do
#    inherit! :search_paths
#    # Pods for testing
#  end

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['BITCODE_GENERATION_MODE'] = 'bitcode'
        end
    end
end
